"""make_candidate_id_nullable_in_submissions

Revision ID: 38c16103b979
Revises: 0ca38986038e
Create Date: 2026-03-03 00:12:54.649595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38c16103b979'
down_revision: Union[str, Sequence[str], None] = '0ca38986038e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('code_submissions', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('code_submissions', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
