"""add thresholds to interview_templates

Revision ID: e9142a940e83
Revises: 933d04d2d5f1
Create Date: 2026-03-26 10:51:11.956991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9142a940e83'
down_revision: Union[str, Sequence[str], None] = '933d04d2d5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_templates', sa.Column('max_duration_minutes', sa.Integer(), server_default='60', nullable=False))
    op.add_column('interview_templates', sa.Column('max_technical_questions', sa.Integer(), server_default='10', nullable=False))
    op.add_column('interview_templates', sa.Column('max_conversational_questions', sa.Integer(), server_default='10', nullable=False))
    op.add_column('interview_templates', sa.Column('max_analytical_questions', sa.Integer(), server_default='10', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_templates', 'max_analytical_questions')
    op.drop_column('interview_templates', 'max_conversational_questions')
    op.drop_column('interview_templates', 'max_technical_questions')
    op.drop_column('interview_templates', 'max_duration_minutes')
    # ### end Alembic commands ###
