"""
Interview Router — Admin-only scheduling endpoints (Refactored for SQLAlchemy)
----------------------------------------------------
POST   /admin/interviews/schedule          – Create a new scheduled interview
PUT    /admin/interviews/{id}/reschedule   – Move interview to a new datetime
PUT    /admin/interviews/{id}/cancel       – Cancel a non-completed interview
"""

import uuid
from fastapi import APIRouter, Depends, status, HTTPException, Query, Body
from sqlalchemy.ext.asyncio import AsyncSession
from typing import List, Optional

from sqlalchemy import select, func
from app.db.sql.models.interview_template import InterviewTemplate
from app.db.sql.models.coding_problem import CodingProblem
from app.db.sql.models.question import Question

from app.api.v1.auth_router import get_current_admin
from app.db.sql.session import get_db_session
from app.db.sql.models.user import User
from app.schemas.interview import (
    ScheduleInterviewRequest,
    ScheduleInterviewResponse,
    RescheduleInterviewRequest,
    RescheduleInterviewResponse,
    CancelInterviewRequest,
    CancelInterviewResponse,
)
from app.schemas.interview_template import TemplatePreviewResponse
from app.services.interview_admin_sql_service import InterviewAdminSQLService
from app.services.template_engine import template_engine
from app.db.sql.enums import InterviewStatus
from app.db.sql.unit_of_work import UnitOfWork

router = APIRouter()

def validate_uuid(id_str: str) -> uuid.UUID:
    try:
        return uuid.UUID(id_str)
    except ValueError:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Invalid UUID: {id_str}",
        )

@router.get(
    "/templates",
    summary="List active interview templates",
    description="Admin-only. Returns all interview templates with is_active=True.",
)
async def list_templates(
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    return await InterviewAdminSQLService.list_active_templates(session)


@router.post(
    "/templates/{template_id}/preview",
    response_model=TemplatePreviewResponse,
    summary="Preview questions generated by a template",
    description="Admin-only. Generates but does not persist questions. If candidate_id is provided, shows LLM-generated questions.",
)
async def preview_template(
    template_id: str,
    candidate_id: Optional[str] = Query(None),
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    validated_id = validate_uuid(template_id)
    template = await session.get(InterviewTemplate, validated_id)
    if not template:
        raise HTTPException(status_code=404, detail="Template not found")

    # Eagerly access all template attributes to prevent lazy loading issues
    # Access all JSON fields while still in async context
    technical_config = template.technical_config if hasattr(template, 'technical_config') else None
    coding_config = template.coding_config if hasattr(template, 'coding_config') else None
    conversational_config = template.conversational_config if hasattr(template, 'conversational_config') else None
    settings = template.settings if hasattr(template, 'settings') else None
    
    # Convert to dict if needed
    if technical_config is None:
        technical_config = {}
    if coding_config is None:
        coding_config = {}
    if conversational_config is None:
        conversational_config = {}
    if settings is None:
        settings = {}

    # 1. Technical Preview — Generate LLM questions if candidate_id provided, otherwise show question bank
    technical_preview = []
    
    # If candidate_id is provided, generate LLM questions (same as what will be used in interview)
    if candidate_id:
        try:
            validated_candidate_id = validate_uuid(candidate_id)
            from app.db.sql.models.user import User
            from app.db.sql.enums import UserRole
            candidate = await session.get(User, validated_candidate_id)
            
            if candidate and candidate.candidate_profile:
                # Get number of technical questions from template config
                num_technical_questions = 6  # Default
                if technical_config and isinstance(technical_config, dict):
                    # Count total questions from difficulty distribution
                    difficulty_dist = technical_config
                    if any(k.lower() in ["easy", "medium", "hard"] for k in difficulty_dist.keys()):
                        num_technical_questions = sum(v for v in difficulty_dist.values() if isinstance(v, int))
                    else:
                        num_technical_questions = technical_config.get("total_questions", 6)
                
                # Get candidate data
                profile = candidate.candidate_profile
                resume_json = profile.resume_json or {}
                jd_json = profile.jd_json or {}
                resume_skills = resume_json.get('skills', []) or profile.skills or []
                jd_skills = jd_json.get('required_skills', []) or jd_json.get('technologies', []) or []
                all_skills = list(set(resume_skills + jd_skills))
                role_name = template.role_name or "Software Engineer"
                
                # Generate LLM questions (same logic as in question_generator_service)
                from app.services.question_generator_service import QuestionGeneratorService
                llm_questions = await QuestionGeneratorService._generate_questions_with_llm(
                    num_questions=num_technical_questions,
                    skills=all_skills,
                    role_name=role_name,
                    resume_data=resume_json,
                    jd_data=jd_json
                )
                
                # Convert to preview format
                for q in llm_questions:
                    technical_preview.append({
                        "question_id": q.get('question_id', str(uuid.uuid4())),
                        "text": q.get('prompt', ''),
                        "difficulty": q.get('difficulty', 'medium').upper(),
                        "category": "TECHNICAL",
                    })
        except Exception as e:
            import logging
            logger = logging.getLogger(__name__)
            logger.warning(f"Failed to generate LLM preview questions: {e}")
            # Fall through to question bank preview
    
    # If no LLM questions generated, fall back to question bank preview
    if not technical_preview:
        technical_questions_res = []
        distribution = None
        if technical_config and isinstance(technical_config, dict):
            # Support both flat map {"easy": 2} and nested {"difficulty_distribution": {"easy": 2}}
            if any(k.lower() in ["easy", "medium", "hard"] for k in technical_config.keys()):
                distribution = technical_config
            else:
                distribution = technical_config.get("difficulty_distribution")

        if not distribution and settings and isinstance(settings, dict):
            distribution = settings.get("difficulty_distribution")

        if distribution and isinstance(distribution, dict):
            from app.db.sql.models.question import DifficultyEnum
            for diff_str, count in distribution.items():
                if not isinstance(count, int) or count <= 0:
                    continue
                
                try:
                    # Resolve enum in Python to avoid database-side cast issues with native enums
                    target_diff = DifficultyEnum(diff_str.upper())
                    
                    # Try full select first (with question_type)
                    try:
                        full_query = select(Question).where(
                            Question.difficulty == target_diff,
                            Question.is_active == True
                        ).order_by(func.random()).limit(count)
                        full_res = await session.execute(full_query)
                        questions = full_res.scalars().all()
                        # Eagerly access all attributes to prevent lazy loading later
                        # Convert to dict-like objects to avoid ORM lazy loading issues
                        from types import SimpleNamespace
                        for q in questions:
                            # Access all attributes while still in async context
                            q_obj = SimpleNamespace()
                            q_obj.id = q.id
                            q_obj.text = q.text
                            q_obj.category = q.category
                            q_obj.difficulty = q.difficulty
                            q_obj.tags = getattr(q, 'tags', None)
                            q_obj.is_active = getattr(q, 'is_active', True)
                            technical_questions_res.append(q_obj)
                    except Exception as db_error:
                        # If question_type doesn't exist, use partial select
                        import logging
                        logger = logging.getLogger(__name__)
                        logger.warning(f"question_type column may not exist, using partial select: {db_error}")
                        # Use partial select without question_type
                        partial_query = select(
                            Question.id, Question.text, Question.category, 
                            Question.difficulty, Question.tags, Question.is_active
                        ).where(
                            Question.difficulty == target_diff,
                            Question.is_active == True
                        ).order_by(func.random()).limit(count)
                        partial_res = await session.execute(partial_query)
                        rows = partial_res.all()
                        # Convert rows to SimpleNamespace objects
                        from types import SimpleNamespace
                        for row in rows:
                            q = SimpleNamespace()
                            q.id = row.id
                            q.text = row.text
                            q.category = row.category
                            q.difficulty = row.difficulty
                            q.tags = row.tags
                            q.is_active = row.is_active
                            technical_questions_res.append(q)
                except (ValueError, Exception) as e:
                    # If one difficulty fails (e.g. invalid key or DB error), 
                    # we log and continue to next section without crashing the whole preview.
                    # However, if it's a DB error, the transaction might be failed.
                    # We're in a simple GET, so we just log.
                    import logging
                    logging.getLogger(__name__).warning(f"Technical preview loop error for {diff_str}: {e}")
                    # Rollback the failed transaction to allow other queries
                    try:
                        await session.rollback()
                    except:
                        pass
                    continue

        # Build technical preview - access attributes safely to avoid lazy loading
        for q in technical_questions_res:
            try:
                # Safely access attributes - handle both Question objects and SimpleNamespace
                question_id = q.id if hasattr(q, 'id') else None
                question_text = q.text if hasattr(q, 'text') else "N/A"
                question_difficulty = q.difficulty if hasattr(q, 'difficulty') else None
                question_category = q.category if hasattr(q, 'category') else None
                
                # Convert enum values to strings if needed
                if hasattr(question_difficulty, 'value'):
                    question_difficulty = question_difficulty.value
                elif hasattr(question_difficulty, 'name'):
                    question_difficulty = question_difficulty.name
                
                if hasattr(question_category, 'value'):
                    question_category = question_category.value
                elif hasattr(question_category, 'name'):
                    question_category = question_category.name
                
                technical_preview.append({
                    "question_id": str(question_id) if question_id else None,
                    "text": question_text,
                    "difficulty": question_difficulty,
                    "category": question_category,
                })
            except Exception as attr_error:
                import logging
                logging.getLogger(__name__).warning(f"Error accessing question attributes in preview: {attr_error}")
                continue

    # 2. Coding Preview
    coding_preview = []
    # Use the already-extracted coding_config to avoid lazy loading
    # coding_config was already extracted at line 77-78, so use that variable
    if isinstance(coding_config, dict):
        count = coding_config.get("count", 0)
        difficulties = coding_config.get("difficulty", [])
        
        if isinstance(count, int) and count > 0 and isinstance(difficulties, list) and difficulties:
            # Normalize difficulties to uppercase for comparison
            valid_diffs = [d.upper() for d in difficulties if isinstance(d, str)]
            
            if valid_diffs:
                try:
                    query = select(CodingProblem).where(
                        func.upper(CodingProblem.difficulty).in_(valid_diffs)
                    ).order_by(func.random()).limit(count)
                    
                    res = await session.execute(query)
                    problems = res.scalars().all()
                    coding_preview = [
                        {
                            "problem_id": p.id,
                            "title": p.title,
                            "difficulty": p.difficulty
                        } for p in problems
                    ]
                except Exception as e:
                    import logging
                    logging.getLogger(__name__).warning(f"Coding preview error: {e}")

    # 3. Conversational Preview
    # Use the already-extracted conversational_config to avoid lazy loading
    # conversational_config was already extracted at line 78, so use that variable
    conv_config = conversational_config if conversational_config else {}
    rounds = conv_config.get("rounds", 0) if isinstance(conv_config, dict) else 0

    conversational_preview = {
        "rounds": rounds if isinstance(rounds, int) else 0,
        "description": "Conversational interview powered by LLM"
    }

    return {
        "technical_section": {"questions": technical_preview},
        "coding_section": {"problems": coding_preview},
        "conversational_section": conversational_preview
    }


@router.get(
    "/summary",
    summary="Get a lightweight summary of all interviews",
    description=(
        "Admin-only. Returns candidate_id, interview_id, status, and scheduled_at "
        "for every interview. Excludes curated_questions for performance."
    ),
)
async def get_interview_summary(
    limit: int = 10,
    offset: int = 0,
    search: str = "",
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    result = await InterviewAdminSQLService.get_interview_summary(session, limit, offset, search)
    data = [
        {
            "interview_id": str(s["interview_id"]),
            "candidate_id": str(s["candidate_id"]) if s["candidate_id"] else None,
            "status": s["status"].value if isinstance(s["status"], InterviewStatus) else s["status"],
            "scheduled_at": s["scheduled_at"],
            "overall_score": s.get("overall_score"),
        }
        for s in result["data"]
    ]
    return {
        "data": data,
        "total": result["total"],
        "limit": limit,
        "offset": offset
    }


@router.post(
    "/schedule",
    response_model=ScheduleInterviewResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Schedule a new interview for a candidate",
    description=(
        "Admin-only. Validates candidate eligibility, checks for existing "
        "active interviews, verifies template, and creates the interview document "
        "with a mock curated questions payload."
    ),
)
async def schedule_interview(
    request: ScheduleInterviewRequest,
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    template_id = validate_uuid(request.template_id)
    candidate_id = validate_uuid(request.candidate_id)
    
    interview = await InterviewAdminSQLService.create_interview(
        session=session,
        template_id=template_id,
        candidate_id=candidate_id,
        assigned_by=current_admin.id,
        scheduled_at=request.scheduled_at,
        questions=request.questions,
    )
    
    return {
        "id": str(interview.id),
        "candidate_id": str(interview.candidate_id),
        "template_id": str(interview.template_id),
        "assigned_by": str(interview.assigned_by),
        "status": interview.status.value if isinstance(interview.status, InterviewStatus) else interview.status,
        "scheduled_at": interview.scheduled_at,
        "curated_questions": interview.curated_questions,
        "created_at": interview.created_at,
    }

@router.put(
    "/{interview_id}/reschedule",
    response_model=RescheduleInterviewResponse,
    status_code=status.HTTP_200_OK,
    summary="Reschedule an existing interview",
    description=(
        "Admin-only. Moves a 'scheduled' interview to a new future datetime. "
        "Returns 409 if status is anything other than 'scheduled'."
    ),
)
async def reschedule_interview(
    interview_id: str,
    request: RescheduleInterviewRequest,
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    validated_id = validate_uuid(interview_id)
    interview = await InterviewAdminSQLService.reschedule_interview(
        session=session,
        interview_id=validated_id,
        scheduled_at=request.scheduled_at,
    )
    
    return {
        "id": str(interview.id),
        "status": interview.status.value if isinstance(interview.status, InterviewStatus) else interview.status,
        "scheduled_at": interview.scheduled_at,
        "updated_at": interview.updated_at,
    }


@router.put(
    "/{interview_id}/cancel",
    response_model=CancelInterviewResponse,
    status_code=status.HTTP_200_OK,
    summary="Cancel an interview",
    description=(
        "Admin-only. Cancels an interview by setting status to 'cancelled'. "
        "The document is never deleted. Returns 409 if status is 'completed'."
    ),
)
async def cancel_interview(
    interview_id: str,
    request: CancelInterviewRequest = CancelInterviewRequest(),
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    validated_id = validate_uuid(interview_id)
    interview = await InterviewAdminSQLService.cancel_interview(
        session=session,
        interview_id=validated_id,
        reason=request.reason,
    )
    
    return {
        "id": str(interview.id),
        "status": interview.status.value if isinstance(interview.status, InterviewStatus) else interview.status,
        "cancelled_at": interview.cancelled_at,
        "reason": interview.cancellation_reason,
    }


@router.get(
    "/{interview_id}/questions",
    summary="Get questions for a scheduled interview",
    description="Admin-only. Returns the curated questions for a scheduled interview.",
)
async def get_interview_questions(
    interview_id: str,
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    """Get questions for a scheduled interview."""
    validated_id = validate_uuid(interview_id)
    interview = await InterviewAdminSQLService.get_interview_details(session, validated_id)
    
    if not interview:
        raise HTTPException(status_code=404, detail="Interview not found")
    
    if not interview.curated_questions:
        return {"questions": []}
    
    questions = interview.curated_questions.get('questions', [])
    return {"questions": questions}


@router.put(
    "/{interview_id}/questions",
    summary="Update questions for a scheduled interview",
    description="Admin-only. Updates the curated questions for a scheduled interview.",
)
async def update_interview_questions(
    interview_id: str,
    questions: List[dict] = Body(...),
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    """Update questions for a scheduled interview."""
    validated_id = validate_uuid(interview_id)
    
    async with UnitOfWork(session) as uow:
        interview = await uow.interviews.get_by_id(validated_id, with_for_update=True)
        
        if not interview:
            raise HTTPException(status_code=404, detail="Interview not found")
        
        if interview.status != InterviewStatus.SCHEDULED:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Can only update questions for scheduled interviews"
            )
        
        # Validate questions
        if not questions or len(questions) == 0:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Interview must contain at least one question"
            )
        
        # Reorder questions to ensure sequential order
        for idx, q in enumerate(questions, 1):
            q['order'] = idx
        
        # Update curated_questions
        if interview.curated_questions:
            interview.curated_questions['questions'] = questions
        else:
            interview.curated_questions = {
                "template_id": str(interview.template_id),
                "generated_from": {},
                "generated_at": interview.created_at.isoformat() + "Z",
                "generation_method": "manual_edit",
                "questions": questions
            }
        
        await uow.flush()
        
        return {"message": "Questions updated successfully", "questions": questions}
